name: hires
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - pandas
  - xlrd
  - geopandas
  - netcdf4
  - xarray
  - scipy
  - matplotlib
  - descartes
  - ipympl
  - seaborn
  - cmocean
  - pip
  - pip:
    - quilt